limit concurrency on single test node show test results on gha finish enable native access for native module Add provider diagnostics for troubleshooting coverage path indicate which provider was found allow user to assert required provider in tests allow easy install of gcc with --auto-install-gcc Require minimum java runtime version for native module (22) Require minimum java version for 'twenty' test (20) pre-check native mode, then run full native build make errors line-specific (break out critical calls) remove .so first when building a new one (not in target) require gcc to enable native module, irrespective of ISA

diff --git a/.github/workflows/unit-tests.yaml b/.github/workflows/unit-tests.yaml
--- a/.github/workflows/unit-tests.yaml
+++ b/.github/workflows/unit-tests.yaml
@@ -12,16 +12,34 @@ on:
       - '**/pom.xml'
 
 jobs:
-  build-avx512-proto:
+  build-avx512:
     concurrency:
-      group: ${{ github.ref }}-${{ github.job }}-${{ matrix.jdk }}-${{ matrix.isa }}
-      cancel-in-progress: true
+      group: ${{ matrix.isa }}-${{ matrix.jdk }}
+      cancel-in-progress: false
     strategy:
       matrix:
-        jdk: [ 11, 20, 22]
+        jdk: [ 20, 24 ]
+#        jdk: [ 24 ]
         isa: [ isa-avx512f ]
     runs-on: ${{ matrix.isa }}
     steps:
+      - name: verify-avx512
+        run: |
+          # avx2 is included just for illustration
+          required="avx2 avx512f avx512cd avx512bw avx512dq avx512v"
+          printf "required ISA feature flags: %s\n" "${required}" 
+          flags="$(lscpu|grep '^Flags'|cut -d: -f2)"
+          output=""
+          for flag in ${required} ; do
+           if [[ " $flags " == *"${flag}"* ]]
+           then output="${output} $flag(OK)"
+           else output="${output} $flag(FAIL)"
+          fi ; done
+          printf "%s\n" ${output}
+          if [[ " $output " == *"FAIL"* ]] ; then exit 2 ; fi
+      - name: Set up GCC
+        run: |
+          sudo apt install -y gcc
       - uses: actions/checkout@v4
       - name: Set up JDK
         uses: actions/setup-java@v3
@@ -29,15 +47,38 @@ jobs:
           java-version: ${{ matrix.jdk }}
           distribution: temurin
           cache: maven
-      - name: Compile, run tests, and package (JDK 22)
-        run: mvn -B verify
-        if: matrix.jdk == '22'
-      - name: Compile, run tests, and package (JDK 20)
-        run: mvn -B -Pjdk20 -am -pl jvector-tests test
+
+      - name: Verify Panama Vector Support
         if: matrix.jdk == '20'
-      - name: Compile and run tests (JDK 11)
-        run: mvn -B -Pjdk11 -am -pl jvector-tests test
-        if: matrix.jdk == '11'
+        run: >-
+          mvn -X -B -Pjdk20 -pl jvector-tests -am test
+          -Dsurefire.failIfNoSpecifiedTests=false
+          -Dtest=TestVectorizationProvider
+          -DTest_RequireSpecificVectorizationProvider=PanamaVectorizationProvider
+      - name: Test Panama Support (JDK 20)
+        run: >-
+          mvn -X -B -Pjdk20 -pl jvector-tests test -am test
+          -DTest_RequireSpecificVectorizationProvider=PanamaVectorizationProvider
+
+      - name: Verify native-access vector support (JDK 24)
+        if: matrix.jdk == '24'
+        run: >-
+          mvn -X -B -Punix-amd64-profile -pl jvector-native -am verify
+          -DTest_RequireSpecificVectorizationProvider=NativeVectorizationProvider
+          -Dsurefire.failIfNoSpecifiedTests=false
+          -Dtest=TestVectorizationProvider
+      - name: Compile, run tests and package (JDK 24)
+        run: >-
+          mvn -X -B -Punix-amd64-profile verify
+          -DTest_RequireSpecificVectorizationProvider=NativeVectorizationProvider
+
+      - name: Test Summary
+        if: always()
+        uses: test-summary/action@v2
+        with:
+          paths: |
+            **/target/surefire-reports/TEST-*.xml
+
 
   build:
     concurrency:
@@ -56,6 +97,10 @@ jobs:
           java-version: ${{ matrix.jdk }}
           distribution: temurin
           cache: maven
+      - name: Set up GCC
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          sudo apt install -y gcc
       - name: Compile, run tests, and package (JDK 22)
         run: mvn -B verify
         if: matrix.jdk == '22'
@@ -65,3 +110,11 @@ jobs:
       - name: Compile and run tests (JDK 11)
         run: mvn -B -Pjdk11 -am -pl jvector-tests test
         if: matrix.jdk == '11'
+      - name: Test Summary
+        if: always()
+        uses: test-summary/action@v2
+        with:
+          paths: |
+            **/target/surefire-reports/TEST-*.xml
+
+        
